# Generated by Django 5.1.1 on 2024-10-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='course_amount',
        ),
    ]
