# Generated by Django 5.1.1 on 2024-10-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_payment_course_amount_alter_payment_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
