# Generated by Django 5.1.1 on 2024-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_college_name_alter_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
