# Generated by Django 5.1.1 on 2024-10-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_college_code'),
        ('student', '0003_student_gender_student_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='home_town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.district'),
        ),
    ]
