# Generated by Django 5.1.1 on 2024-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_hometown_student_home_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
